name: antizero_jumpin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.0+5

environment:
  sdk: '>=2.9.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.19.2
  firebase_auth: ^3.6.1
#  firebase_crashlytics: ^2.0.3
  lottie: any
#  google_sign_in: ^5.0.3
#  cloud_firestore: ^2.1.0
  firebase_storage: ^10.3.3
  #for Either in value_objects
  #used for union of failures in valueOobjects
  freezed_annotation: ^2.1.0
  page_transition: ^2.0.2
  get_it: ^7.1.3
#  into_phone_field: ^2.0.0
  flutter_swiper: ^1.1.6
  device_preview: any
  percent_indicator: ^4.2.2
  flutter_spinkit: ^5.0.0
  data_connection_checker: ^0.3.4
  geoflutterfire: any
  day_night_time_picker: ^1.0.2
  share_plus: ^4.0.10
  http: ^0.13.3
  path_provider: ^2.0.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.7.0
  provider: ^6.0.0
  rxdart: ^0.27.0
  contacts_service: ^0.6.1
  liquid_progress_indicator: ^0.4.0
  firebase_dynamic_links: ^4.3.3
#  app_settings: ^4.1.0
  emoji_feedback: ^0.1.0
  country_list_pick: ^1.0.1+4
  devicelocale: ^0.5.4
  #  cached_network_image: any
  cached_network_image: ^3.1.0
  jiffy: ^5.0.0
  floating_action_bubble: ^1.1.2
#  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  loading_indicator: ^3.1.0
  flutter_datetime_picker: ^1.5.1
  json_annotation: ^4.0.1
  fluttertoast: ^8.0.7
  uuid: ^3.0.4
  date_format: ^2.0.2
  intl: ^0.17.0
  expand_widget: ^2.1.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.5
 # image_cropper: ^2.0.3
  screenshot: ^1.2.3
#  open_settings: ^2.0.2
  webview_flutter: ^3.0.4
  open_settings: ^2.0.1
  rename: ^2.0.1
  firebase_remote_config: ^2.0.13
  package_info_plus: ^1.3.0
  upgrader: ^4.4.2
#  photo_manager: ^1.3.9+1
#  flutter_neumorphic: ^3.0.4
  cloud_firestore:
#  cloud_firestore: ^2.5.4
  the_apple_sign_in: ^1.1.1
  flutter_keyboard_visibility: ^5.1.0
  adaptive_dialog: any
  url_launcher: ^6.0.17
  firebase_analytics: ^9.0.4
  timeago: ^3.1.0
  any_link_preview: ^2.0.2
  georange: ^1.0.0
  scrollable_positioned_list: ^0.3.2
  flutter_app_badger: ^1.3.0
  emoji_picker_flutter: ^1.3.0
  scroll_to_index: ^3.0.1
#  facebook_app_events: ^0.16.0
  video_player: ^2.4.0
  csv: ^5.0.0
  google_fonts: ^3.0.1
  sizer: ^2.0.15
  flutter_svg: ^1.0.3
  eva_icons_flutter: ^3.1.0
  linkwell: ^2.0.6
 # flutter_sound: ^8.1.9
  flutter_sound: ^9.2.13
  assets_audio_player: ^3.0.3+3
  dependency_validator: ^3.2.2
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  simple_animations: ^1.3.3
  awesome_notifications: ^0.6.21
  geolocator: any
  google_maps_flutter: ^2.2.0
  image_cropper: ^3.0.0
  google_sign_in: ^5.4.1
  shared_preferences: ^2.0.15

dependency_overrides:
  #platform: ^3.1.0
  #permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.9.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
#  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon_square.png"

  # adaptive_icon_background: "assets/icon/android_launcher_bg.png"
  # adaptive_icon_foreground: "assets/icon/rsz_logo_white.png"




# The following section is specific to Flutter.
flutter:
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet MS.ttf
        - asset: assets/fonts/SFUIText-Bold.ttf
        - asset: assets/fonts/SFUIText-Semibold.ttf

    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal-Light.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCereal-Book.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCereal-Medium.ttf
          weight: 500
        - asset: assets/fonts/AirbnbCereal-Bold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCereal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCereal-Black.ttf
          weight: 900

  uses-material-design: true

  assets:
    - assets/images/Home/
    - assets/images/
    - assets/images/Onboarding/
    - assets/images/OnBoard/
    - assets/animations/
    - assets/images/SideNav/
    - assets/images/Onboarding/Interests/outdoor-sports/
    - assets/images/Onboarding/Interests/indoor-sports/
    - assets/images/Onboarding/Interests/academic/
    - assets/images/Onboarding/Interests/causes-passionate-about/
    - assets/images/Onboarding/Interests/competitve-exams/
    - assets/images/Onboarding/Interests/entertainment/
    - assets/images/Onboarding/Interests/fandoms/
    - assets/images/Onboarding/Interests/foods-&-drinks/
    - assets/images/Onboarding/Interests/games/
    - assets/images/Onboarding/Interests/health-&-fitness/
    - assets/images/Onboarding/Interests/hobbies/
    - assets/images/Onboarding/Interests/miscellaneous/
    - assets/images/Onboarding/Interests/travel-&-adventure/
    - assets/images/Onboarding/Interests/career/
    - assets/images/Profile/
    - assets/images/chats/
    - assets/images/plans/
    - assets/images/people/
    - assets/icon/
    - assets/people/
    - assets/videos/jumpin_video.mp4